### ISSUE TITLE
Behavior of read_table with rows of unequal length

### ISSUE THREAD

**Issue by joranE** [hadley/readr#169] opened 2015-05-13 22:24 UTC
I was looking at [this](http://stackoverflow.com/q/30225411/324364) StackOverflow question. I don't see any equivalent of `read.table`'s `fill` argument, which is fine, but I was surprised by the default behavior in this case:

    read_table(file = "GroupA Whatever1 A B C
     GroupB Whatever2 C D
     GroupC Whatever3 E F G H",col_names = FALSE)
          X1        X2 X3 X4 X5 X6
    1 GroupA Whatever1  A  B  C  G
    2 GroupC Whatever3  E  F  G  H

I thought maybe I could read just the first two columns:

    read_table(file = "GroupA Whatever1 A B C
     GroupB Whatever2 C D
     GroupC Whatever3 E F G H",col_names = FALSE,col_types = "cc____")
          X1        X2
    1 GroupA Whatever1
    2 GroupC Whatever3

...but only kind of it seems.

I'm not sure if/how you planned on handling rows of unequal length, but perhaps at least a warning or error would be better than this behavior...?

**Comment by hadley** [comment] 2015-09-03 19:38
Duplicate of #189

**Closed by hadley** 2015-09-03 19:38 UTC
