### ISSUE TITLE
read_csv converts negative values to positives without warnings

### ISSUE THREAD

**Issue by ctmann** [hadley/readr#358] opened 2016-02-02 14:12 UTC
read_csv converts  negative values to positives without warnings, making import data unreliable.

Example: "-3,000" imports as "3000" 
Example: "-4000" imports as "4000"

(Simple .csv file attached)
[testbed.zip](https://github.com/hadley/readr/files/114042/testbed.zip)

**Comment by hadley** [comment] 2016-06-01 20:58
Duplicate of #308

**Closed by hadley** 2016-06-01 20:58 UTC
