### ISSUE TITLE
support UTF-8 fules, allow the 'encoding' option in read_csv

### ISSUE THREAD

**Issue by lucasmation** [hadley/readr#191] opened 2015-06-10 17:36 UTC
read_csv is great. But does not allow me to read my UTF-8 (portuguese caracters) correctly. That would be great. Tks!

**Comment by larmarange** [comment] 2015-07-05 14:14
This issue seems general, as the same problem occurs with `read_file` or `read_delim`

**Comment by larmarange** [comment] 2015-07-05 14:17
This issue seems to be a duplicate of https://github.com/hadley/readr/issues/40

**Closed** 2015-07-05 16:47 UTC
