### ISSUE TITLE
Trailing \r on Windows

### ISSUE THREAD

**Issue by zross** [hadley/readr#97] opened 2015-03-20 19:13 UTC
Hi Hadley, very excited to have this package, thank you.

Apologies if there is something I'm missing. I'm getting a trailing \r in using read_csv() where I don't have this with read.csv(). 

    write.csv(mtcars[1:3,], "mtcars.csv", row.names=FALSE) # same thing with write_csv()
    read_csv("mtcars.csv")
    mpg cyl disp  hp drat    wt  qsec vs am gear carb"
    1 21.0   6  160 110 3.90 2.620 16.46  0  1    4   4\r
    2 21.0   6  160 110 3.90 2.875 17.02  0  1    4   4\r
    3 22.8   4  108  93 3.85 2.320 18.61  1  1    4   1\r

    read.csv("mtcars.csv")
    mpg cyl disp  hp drat    wt  qsec vs am gear carb
    1 21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
    2 21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
    3 22.8   4  108  93 3.85 2.320 18.61  1  1    4    1

    > sessionInfo()
    R version 3.1.2 (2014-10-31)
    Platform: x86_64-w64-mingw32/x64 (64-bit)

    locale:
    [1] LC_COLLATE=English_United States.1252 
    [2] LC_CTYPE=English_United States.1252   
    [3] LC_MONETARY=English_United States.1252
    [4] LC_NUMERIC=C                          
    [5] LC_TIME=English_United States.1252    

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     

    other attached packages:
    [1] readr_0.0.0.9000

    loaded via a namespace (and not attached):
    [1] Rcpp_0.11.5 tools_3.1.2

**Comment by daattali** [comment] 2015-03-22 00:32
I just tried using `read.csv` for the first time and I'm also seeing this problem, also on Windows.  Using the example that @zross used, I get the same output.  But using my real data that was copied over from a different machine, I'm also getting a trailing `\r`  appended to the name of the last column name

Example (sorry for not providing an actual reproducible example, this is only to show the output)
```
> head(wDat, 3)
Source: local data frame [3 x 3]

  Amplitude1 Amplitude2 Cluster\r
1   426.6829   503.1551       1\r
2   764.0446   908.7441       1\r
3   826.5894  1054.3832       1\r
```

**Comment by hadley** [comment] 2015-03-31 15:22
Duplicate of #87

**Closed by hadley** 2015-03-31 15:22 UTC
