### ISSUE TITLE
Better column skip function

### ISSUE THREAD

**Issue by MySchizoBuddy** [hadley/readr#209] opened 2015-06-28 02:34 UTC
Request for a better column skip syntax because the below is getting ridiculous and *slow* to execute

```
data <- read_csv("data/690150TY.csv", skip = 1, col_types = list(
  `Date (MM/DD/YYYY)` = col_date("%m/%d/%Y"),
  `GHI source` = col_skip(),
  `DNI source` = col_skip(),
  `DHI source` = col_skip(),
  `GH illum (lx)` = col_skip(),
  `GH illum source` = col_skip(),
  `Global illum uncert (%)` = col_skip(),
  `DN illum (lx)` = col_skip(),
  `DN illum source` = col_skip(),
  `DN illum uncert (%)` = col_skip(),
  `DH illum (lx)` = col_skip(),
  `DH illum source` = col_skip(),
  `DH illum uncert (%)` = col_skip(),
  `Zenith lum (cd/m^2)` = col_skip(),
  `Zenith lum source` = col_skip(),
  `Zenith lum uncert (%)` = col_skip())
  )
``` 
I'm not even done yet, lot more columns to skips. I cannot use the (dc____d) syntax because some columns are date time and factors. 
The best way now is to read all columns and then use dataframe subsetting to get the columns I want.

**Comment by hadley** [comment] 2015-07-04 08:51
Duplicate of #72

**Closed by hadley** 2015-07-04 08:51 UTC
