### ISSUE TITLE
parsing failure- read_fwf includes a column of NAs when told to ignore the column?

### ISSUE THREAD

**Issue by ajdamico** [hadley/readr#322] opened 2015-11-27 09:19 UTC
sorry if i'm misreading something.  thanks!

	library(readr)
	fwf_sample <- system.file("extdata/fwf-sample.txt", package = "readr")
	cat(read_lines(fwf_sample))

	# works
	read_fwf(fwf_sample, fwf_widths(c(2, 5, 3)),col_types='ddd')

	# includes a column of NAs because the column contains data even though it was told to skip?
	read_fwf(fwf_sample, fwf_widths(c(2, 5, 3)),col_types='d-d')

**Comment by mlaviolet** [comment] 2015-12-30 18:31
I ran into the same problem, getting parsing errors while trying to read selected fields from a large BRFSS survey data file. Took a couple of hours to realize what was happening. The help page for read_fwf now says "The width of the last column will be silently extended to the next line break" so R reads the entire remainder of the line following what's supposed to be the last field. I don't understand the rationale for this change; the old behavior needs to be restored or an argument added to say "I'm done, go to the next line."

**Comment by ajdamico** [comment] 2015-12-30 18:34
( @mlaviolet unrelated to this issue but you can just let this brfss import run overnight and not worry about it.  https://github.com/ajdamico/asdfree/tree/master/Behavioral%20Risk%20Factor%20Surveillance%20System )

**Comment by mlaviolet** [comment] 2016-01-05 14:24
Hi Anthony, 

Thanks for your note. I was able to create the design objects for 2011-14 with your "download all microdata" script. The queries using dbGetQuery from the "2011 single-year - analysis examples" script were quite fast, but when I tried to use the survey functions I got an error:: 

> svymean( ~age , brfss.d , na.rm = TRUE ) 
Error in checkConnection(dbconnection) : 
could not find function "isIdCurrent" 

It worked once I loaded the RMySQL package , but it was very slow (about five minutes). Does the script need revision, or did I miss something? 

If this helps, the documentation for RMySQL says: "isIdCurrent will be deprecated in the near future; please use the dbIsValid() generic instead." 

Thanks, 
Mike Laviolette 
----- Original Message -----

**Comment by ghaarsma** [comment] 2016-01-19 05:57
A temporary workaround, is to first create the col_positions and then remove the column names that you don't need. 
```R
fwf_sample <- system.file("extdata/fwf-sample.txt", package = "readr")
cat(read_lines(fwf_sample))
col_positions <- fwf_widths(c(2, 5, 3))
col_types <- 'd-d'

col_positions$col_names <- col_positions$col_names[!strsplit(col_types,'')[[1]] %in% c('_','-')]

read_fwf(fwf_sample,col_positions = col_positions ,col_types = col_types)
```
Note that there are other issues with the read_fwf (See https://github.com/hadley/readr/issues/300) that can be related.

**Comment by hadley** [comment] 2016-06-02 02:51
Duplicate of #300

**Comment by hadley** [comment] 2016-06-02 11:48
Deleted the irrelevant comments

**Closed** 2016-07-13 18:08 UTC
