### ISSUE TITLE
UTF8/character encoding

### ISSUE THREAD

**Issue by aghaynes** [hadley/readr#164] opened 2015-05-05 08:12 UTC
Hi,
readr is great! So much faster than using read.xxx()! 
Is there any chance of character encoding support, similar to read.table encoding = "..." argument?

I'm working in Switzerland and of course most files have ü or ä or ö somewhere in them...with read_csv for instance I get ZusÃ¤tze rather than Zusätze. UTF8 encoding generally sorts this out.

Thanks!

Alan

**Comment by hadley** [comment] 2015-05-05 11:59
Duplicate of #40

**Closed by hadley** 2015-05-05 11:59 UTC
