### ISSUE TITLE
Character encoding problems with write_csv

### ISSUE THREAD

**Issue by andrewdolman** [hadley/readr#227] opened 2015-08-03 15:07 UTC
I'm having similar character encoding problems with readr as I had with dplyr (https://github.com/hadley/dplyr/issues/951, now resolved). 

```
df <- data.frame(Lake = c("Lake1", "Lake2"), Gewässer = c("Gewässer1", "Gewässer2"))

library(readr)

write.csv(df, "df_base.csv", row.names = FALSE)
write_csv(df, "df_readr.csv")

# read base version
read.csv("df_base.csv")
```
   Lake  Gewässer
1 Lake1 Gewässer1
2 Lake2 Gewässer2

```
# read readr version
read.csv("df_readr.csv")
```
   Lake  GewÃ.sser
1 Lake1 GewÃ¤sser1
2 Lake2 GewÃ¤sser2
```
# Again using read_csv
read_csv("df_base.csv")
```
   Lake  Gewässer
1 Lake1 Gewässer1
2 Lake2 Gewässer2
```
read_csv("df_readr.csv")
```
   Lake  GewÃ¤sser
1 Lake1 GewÃ¤sser1
2 Lake2 GewÃ¤sser2

```
sessionInfo()
```
R version 3.2.0 (2015-04-16)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ndb2_0.0.0.9001  readr_0.1.1.9000

loaded via a namespace (and not attached):
[1] tools_3.2.0 Rcpp_0.12.0

**Comment by hadley** [comment] 2015-08-03 15:19
Duplicate of #40

**Closed by hadley** 2015-08-03 15:19 UTC
