### ISSUE TITLE
Allow for multiple na values

### ISSUE THREAD

**Issue by markdanese** [hadley/readr#190] opened 2015-06-10 17:15 UTC
Right now only a single value can be converted to NA.  I have a dataset where there are 3 possible missing values, -9, -8, -7. They refer to different reasons for missing, but in the end, they are all NA.  I tried using na = c("-9", "-8", "-7") but received an error that the function was expecting a single value.

**Comment by jennybc** [comment] 2015-06-14 05:41
Duplicate of #125

**Comment by markdanese** [comment] 2015-06-14 06:48
thanks.  I searched but did not see that.

**Closed** 2015-06-14 06:48 UTC
