### ISSUE TITLE
not sure if col_types= "_" and col_names= parameters align properly?

### ISSUE THREAD

**Issue by ajdamico** [hadley/readr#323] opened 2015-11-27 09:25 UTC
this behavior seems odd to me?  not sure how someone would correctly specify 1,2,3,5 named columns while skipping that 4th column?  this might only be a problem for people trying to shift their `read.fwf` calls over to `readr::read_fwf` though..thanks!

	library(readr)
	fwf_sample <- system.file("extdata/fwf-sample.txt", package = "readr")
	new_sample <- paste0( read_lines( fwf_sample ) , "  1" )
	writeLines( new_sample , tf <- tempfile() )

	# works
	read_fwf(tf, fwf_widths(c(2, 5, 3, 2, 1)))

	# works
	read_fwf(tf, fwf_widths(c(2, 5, 3, 2, 1),col_names=c('a','b','c','d','e')),col_types='ddddd')

	# incorrectly creates a column of NAs?
	read_fwf(tf, fwf_widths(c(2, 5, 3, 2, 1)),col_types='ddd-d')

	# incorrectly creates a column of NAs?
	read_fwf(tf, fwf_widths(c(2, 5, 3, 2, 1),col_names=c('a','b','c','d','e')),col_types='ddd-d')

	# incorrectly fails because i did not specify a column name for the field i specified to skip?
	read_fwf(tf, fwf_widths(c(2, 5, 3, 2, 1),col_names=c('a','b','c','e')),col_types='ddd-d')

**Comment by hadley** [comment] 2016-06-02 02:51
Duplicate of #300

**Closed by hadley** 2016-06-02 02:51 UTC

**Comment by hadley** [comment] 2016-06-02 02:53
Oops actually duplicate of #322
