### ISSUE TITLE
readr does not install

### ISSUE THREAD

**Issue by meyera** [hadley/readr#108] opened 2015-04-06 12:56 UTC
Dear Hadley, the current version (6th April 2015) of readr will not install on my system. Following the error and my session information.
Thank you so much,
Alex

```
> devtools::install_github("hadley/readr")
Downloading github repo hadley/readr@master
Installing readr
"C:/PROGRA~1/R/R-31~1.2/bin/x64/R" --vanilla CMD INSTALL  \
  "C:/Users/Alexander/AppData/Local/Temp/RtmpUBJnpi/devtools1f0c3fdb7222/hadley-readr-d122be0"  \
  --library="C:/Users/Alexander/Documents/R/win-library/3.1" --install-tests 

* installing *source* package 'readr' ...
** libs
g++ -m64 -I"C:/PROGRA~1/R/R-31~1.2/include" -DNDEBUG    -I"C:/Users/Alexander/Documents/R/win-library/3.1/Rcpp/include" -I"C:/Users/Alexander/Documents/R/win-library/3.1/BH/include" -I"d:/RCompile/CRANpkg/extralibs64/local/include"     -O2 -Wall  -mtune=core2 -c Collector.cpp -o Collector.o
In file included from DateTimeLocale.h:5:0,
                 from DateTime.h:6,
                 from CollectorDateTime.h:6,
                 from Collector.cpp:13:
Iconv.h: In member function 'std::string Iconv::convert(std::string)':
Iconv.h:41:73: error: invalid conversion from 'char**' to 'const char**' [-fpermissive]
C:/PROGRA~1/R/R-31~1.2/include/iconv.h:53:8: error:   initializing argument 2 of 'size_t libiconv(libiconv_t, const char**, size_t*, char**, size_t*)' [-fpermissive]
In file included from CollectorDateTime.h:6:0,
                 from Collector.cpp:13:
DateTime.h: In member function 'void TzManager::setTz(std::string)':
DateTime.h:32:20: error: 'unsetenv' was not declared in this scope
DateTime.h:34:33: error: 'setenv' was not declared in this scope
make: *** [Collector.o] Error 1
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-31~1.2/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-31~1.2/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="readr.dll" WIN=64 TCLBIN=64 OBJECTS="Collector.o DateTimeLocale.o DateTimeParser.o RcppExports.o Source.o Tokenizer.o TokenizerFwf.o connection.o datetime.o parse.o read.o type_convert.o write_csv.o"' had status 2
ERROR: compilation failed for package 'readr'
* removing 'C:/Users/Alexander/Documents/R/win-library/3.1/readr'
* restoring previous 'C:/Users/Alexander/Documents/R/win-library/3.1/readr'
Error: Command failed (1)
```

```
> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] bitops_1.0-6   devtools_1.7.0 evaluate_0.5.5 formatR_1.0    httr_0.6.1     knitr_1.9      RCurl_1.95-4.5 stringr_0.6.2  tools_3.1.2   
>
```

**Comment by hadley** [comment] 2015-04-06 15:01
Duplicate of #107

**Closed by hadley** 2015-04-06 15:01 UTC
