### ISSUE TITLE
type_convert only touches character columns; doesn't check/subset col_types accordingly

### ISSUE THREAD

**Issue by jennybc** [hadley/readr#369] opened 2016-02-22 06:17 UTC
``` r
library(readr)
suppressPackageStartupMessages(library(dplyr))
```

If you can use `read_csv()`, the automatic variable type detection is great.

``` r
read_csv("integer,logical\n1,TRUE\n2,FALSE\n")
#> Source: local data frame [2 x 2]
#> 
#>   integer logical
#>     (int)   (lgl)
#> 1       1    TRUE
#> 2       2   FALSE
```

I understand `type_convert()` is meant to do similar when you're stuck with a *data frame* that needs Hadleyverse type (re-)conversion.

``` r
(df <- data_frame(integer = c(1, 2),
                  logical = c("TRUE", "FALSE")))
#> Source: local data frame [2 x 2]
#> 
#>   integer logical
#>     (dbl)   (chr)
#> 1       1    TRUE
#> 2       2   FALSE
```

Right now, only character columns are re-processed. Could all columns be re-processed? At least when `col_types = NULL`?

``` r
type_convert(df)
#> Source: local data frame [2 x 2]
#> 
#>   integer logical
#>     (dbl)   (lgl)
#> 1       1    TRUE
#> 2       2   FALSE
```

Also, if you specify `col_types`, it's not actually checked/subsetted against the character columns, so you get warnings and an incorrect result.

``` r
type_convert(df, col_types = "il")
#> Warning: Insufficient `col_names`. Adding 1 names.
#> Warning in type_convert_col(char_cols[[i]], col_types[[i]],
#> which(is_character)[i], : [0, 2]: expected an integer, but got 'TRUE'
#> Warning in type_convert_col(char_cols[[i]], col_types[[i]],
#> which(is_character)[i], : [1, 2]: expected an integer, but got 'FALSE'
#> Source: local data frame [2 x 2]
#> 
#>   integer logical
#>     (dbl)   (int)
#> 1       1      NA
#> 2       2      NA
```

Current workaround is to make sure everything is character prior to use of `type_convert()`.

``` r
df[] <- lapply(df, as.character)
type_convert(df)
#> Source: local data frame [2 x 2]
#> 
#>   integer logical
#>     (int)   (lgl)
#> 1       1    TRUE
#> 2       2   FALSE
```

This may be related to what this person was talking about? Hard to tell. <https://github.com/hadley/readr/pull/160>

**Comment by hadley** [comment] 2016-06-01 21:47
The problem is that there's no logic in readr to simplify anything other than character columns, so I think (e.g.) converting double to integer is out of scope (unless that is legitimately the only conversion, in which we could make a special case).

We definitely need to rethink how `col_types` works in this scenario.

**Comment by hadley** [comment] 2016-06-08 18:18
@jimhester I think the main thing here is probably to not allow character specification of column types

**Closed** 2016-06-14 19:25 UTC
Labels: enhancement, in progress
