### ISSUE TITLE
read_csv() not reading in data in some columns for unknown reason

### ISSUE THREAD

**Issue by dsself** [hadley/readr#215] opened 2015-07-07 20:11 UTC
I'm currently using readr 0.1.1 and have had the issue of reading in csv but some, not all, columns read in with all values as NA.  

With this [sample](https://github.com/dsself/V-dem/blob/master/Example.csv) you can see that 

```
d1 <- read_csv(Example.csv) %>%
count(fsqg_178)
```
returns all NAs but

```
d1 <- read.csv(Example.csv, stringsAsFactors = FALSE) %>%
count(fsqg_178)
```
returns the correct count of the objects. 

Also, the other column `fsqg_1` included in the csv returns the same counts using `read_csv` and `read.csv`. I also checked and  `is.character` returns  `TRUE` for both  `fsqg_1` and  `fsqg_178`

**Comment by slightlydeviant** [comment] 2015-07-10 14:41
I had this problem as well, but it is an easy fix. ``read_csv`` scans the first 100 rows and decides which data type to use for each column. Because the first 100 rows are missing in your second column, it uses the class "logical". Try defining your ``col_types`` in ``read_csv``.

    read_csv(Example.csv, col_types = "cc")

**Comment by dsself** [comment] 2015-07-10 14:57
Unfortunately I'm working with a csv that has over 1700 columns, many of them with the first 100 rows empty.

**Comment by VectorPosse** [comment] 2015-07-24 18:55
I have the exact same issue as dsself. I am working with over 1000 columns and there's no way I'm going to specify the column types for each.

I'm all for the scanning heuristic to detect data types. It seems dangerous for this heuristic to be applied to seemingly empty columns.

**Comment by hadley** [comment] 2015-07-24 21:21
Until I fix this you can just rep or similar to specify all the types.

**Comment by hadley** [comment] 2015-09-03 19:22
Duplicate of #204

**Closed** 2015-09-03 19:22 UTC

**Comment by mohanwugupta** [comment] 2018-06-08 18:30
I thought I had a similar problem and then realized that there is a limit for how many variables on displayed when using View(dataframe)...
