### ISSUE TITLE
Compilation error - iconv

### ISSUE THREAD

**Issue by rohlfs** [hadley/readr#139] opened 2015-04-17 16:39 UTC
I could not compile the package:
uname -a
FreeBSD  9.2-RELEASE-p3 amd64

install.package("readr")

In file included from DateTimeLocale.h:5:0,
                 from DateTime.h:6,
                 from CollectorDateTime.h:6,
                 from Collector.cpp:13:
Iconv.h: In member function 'std::string Iconv::convert(std::string)':
Iconv.h:47:73: error: invalid conversion from 'char**' to 'const char**' [-fpermissive]
     size_t res = iconv(cd_, &inbuf, &inbytesleft, &outbuf, &outbytesleft);
                                                                         ^
In file included from Iconv.h:4:0,
                 from DateTimeLocale.h:5,
                 from DateTime.h:6,
                 from CollectorDateTime.h:6,
                 from Collector.cpp:13:
/usr/local/include/iconv.h:83:15: error:   initializing argument 2 of 'size_t libiconv(libiconv_t, const char**, size_t*, char**, size_t*)' [-fpermissive]
 extern size_t iconv (iconv_t cd, const char* * inbuf, size_t *inbytesleft, cha
               ^
/usr/local/lib/R/etc/Makeconf:129: recipe for target 'Collector.o' failed
gmake: *** [Collector.o] Error 1
ERROR: compilation failed for package 'readr'

**Comment by hadley** [comment] 2015-04-17 18:21
Gah, iconv is pain. 

@jeroeonooms, any ideas? Maybe we need to check for the gnu compiler flag?

**Comment by hadley** [comment] 2015-07-09 18:17
Duplicate of #149

**Closed by hadley** 2015-07-09 18:17 UTC
