### ISSUE TITLE
add comment_char argument to skip lines beginning with a comment marker?

### ISSUE THREAD

**Issue by rpruim** [hadley/readr#167] opened 2015-05-08 21:28 UTC
This could be used to read files that include commented sections that provide meta data and would function like `comment.char` from `read.csv()`.

**Comment by smbache** [comment] 2015-05-09 10:42
+1

**Comment by jennybc** [comment] 2015-05-24 06:02
:+1:

**Comment by sjackman** [comment] 2015-06-19 23:10
:+1: Duplicate of #68

**Closed** 2015-06-20 03:47 UTC
