### ISSUE TITLE
incorrect reading by read_delim, read_csv

### ISSUE THREAD

**Issue by Kushdesh** [hadley/readr#307] opened 2015-11-03 12:14 UTC
```R
a <- readr::read_delim("A,B\n4,5G", delim = ",")
```
returns 2nd column as numeric 5 whereas I was expecting character 5G. This error happens when any column has all its element either blank or numbers followed by **exactly one** character.

**Comment by hadley** [comment] 2016-06-02 02:50
Duplicate of #308

**Closed by hadley** 2016-06-02 02:50 UTC
