### ISSUE TITLE
Problem with read_csv2 and negative values using comma as decimal separator

### ISSUE THREAD

**Issue by dickoa** [hadley/readr#151] opened 2015-04-24 16:14 UTC
There's  a problem with the `read_csv2` function when we have a negative values with comma as decimal separator. Here are some examples:

This works because there is no negative values

```{r}
library(readr)
str(read_csv2("a;b\n1,0;2,0"))
## Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	1 obs. of  2 variables:
##  $ a: num 1
##  $ b: num 2
```

Then this fails

```{r}
str(read_csv2("a;b\n-1,0;2,0"))
## Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	1 obs. of  2 variables:
##  $ a: chr "-1,0"
##  $ b: num 2
```

And if we use a `.` as decimal separator it works again

```{r}
str(read_csv2("a;b\n-1.0;2,0"))
## Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	1 obs. of  2 variables:
##  ## $ a: num -1
##  ## $ b: num 2
```
If I missed something in the documentation, just let me know and thanks again for the `readr` package.

**Comment by hadley** [comment] 2015-07-10 04:16
Duplicate of #213 and now fixed :)

**Closed by hadley** 2015-07-10 04:16 UTC
