### ISSUE TITLE
Column detection specification problem in read_fwf

### ISSUE THREAD

**Issue by adamdsmith** [hadley/readr#298] opened 2015-10-22 20:31 UTC
Since 0.2.0, `read_fwf` is having trouble parsing some text files that it previously (0.1.1) handled without any problem.

For example:
```
text <- "F Latitude   Longitude   Alt(m)   Date       Time     S\r\nT N37.6 W089.0    201.1 1969-12-31 20:54:04 1\r\nT N37.6 W089.0    201.1 1969-12-31 20:54:05 0\r\n"

col_pos <- fwf_empty(text, skip = 1)
```

As expected, there are seven columns.

```
col_pos         
$begin
[1]  0  2  8 18 24 35 44

$end
[1]  1  7 14 23 34 43 45

$col_names
[1] "X1" "X2" "X3" "X4" "X5" "X6" "X7"
```

`read_fwf` works with readr 0.1.1:
```
works <- read_fwf(text, col_pos, col_types = "_ccncc_", skip = 1)
works
     X2     X3    X4         X5       X6
1 N37.6 W089.0 201.1 1969-12-31 20:54:04
2 N37.6 W089.0 201.1 1969-12-31 20:54:05
```

`read_fwf` has parsing issues in readr 0.2.0 through 0.2.2.  In this case it
tacks on an extra column of `NA`s: 
```
doesnt <- read_fwf(text, col_pos, col_types = "_ccncc_", skip = 1)

Warning: 2 parsing failures.
row col  expected    actual
1  -- 8 columns 7 columns
2  -- 8 columns 7 columns
Warning message:
    Insufficient `col_types`. Guessing 2 columns.

doesnt
     X2     X3    X4         X5       X6   NA
1 N37.6 W089.0 201.1 1969-12-31 20:54:04 <NA>
2 N37.6 W089.0 201.1 1969-12-31 20:54:05 <NA> 
```

**Comment by adamdsmith** [comment] 2016-01-06 18:21
Sorry, not able to attempt an adequate PR, but the following changes to `col_spec_standardise` in `R/col_types.R` fixed my specific issue documented above.  It also seems to work with every specification I can throw at it.

Specifically, here is the modified code (lines 161-183 of `col_types.R`) , with the two changed lines marked `### CHANGED` above the `### ORIGINAL` line:

    } else if (is.null(type_names) && !guessed_names) {
      # unnamed types & names supplied: match non-skipped columns
      skipped <- vapply(spec$cols, inherits, "collector_skip",
                        FUN.VALUE = logical(1))
      n_read <- sum(!skipped)
      n_names <- length(col_names[!skipped])  ### CHANGED
      # n_names <- length(col_names)  ### ORIGINAL
      
      n_new <- abs(n_names - n_read)
      if (n_read < n_names) {
        warning("Insufficient `col_types`. Guessing ", n_new, " columns.",
                call. = FALSE)
        spec$cols <- c(spec$cols, rep(list(col_guess()), n_new)) ### CHANGED
        # spec$cols <- c(spec$cols, list(rep(col_guess(), n_new))) ### ORIGINAL
        # This change wasn't directly relevant, but I noticed that list(rep(col_guess(), n_new) didn't
        # seem to be giving the desired output (i.e., increasing length(spec$cols) by n_new)
      } else if (n_read > n_names) {
        warning("Insufficient `col_names`. Adding ", n_new, " names.",
                call. = FALSE)
        col_names <- c(col_names, paste0("X", seq_len(n_new) + n_read - 1))
      } else {
        col_names2 <- rep("", length(spec$cols))
        col_names2[!skipped] <- col_names[!skipped]
        col_names <- col_names2
      }
      names(spec$cols) <- col_names
    } else {

**Comment by adamdsmith** [comment] 2016-01-06 18:51
And some examples with the changes...

    text <- "F Latitude   Longitude   Alt(m)   Date       Time     S\r\nT N37.6 W089.0    201.1 1969-12-31 20:54:04 1\r\nT N37.6 W089.0    201.1 1969-12-31 20:54:05 0\r\n"
    col_pos <- fwf_empty(text, skip = 1)

    read_fwf(text, col_pos, col_types = "_ccncc_", skip = 1)
         X2     X3    X4         X5       X6
    1 N37.6 W089.0 201.1 1969-12-31 20:54:04
    2 N37.6 W089.0 201.1 1969-12-31 20:54:05
    
    read_fwf(text, col_pos, col_types = "_c_?cc_", skip = 1)
         X2    X4         X5       X6
    1 N37.6 201.1 1969-12-31 20:54:04
    2 N37.6 201.1 1969-12-31 20:54:05
    
    read_fwf(text, col_pos, skip = 1)
    Warning: 2 parsing failures.
    row col   expected   actual
      1  X6 valid date 20:54:04
      2  X6 valid date 20:54:05
        X1    X2     X3    X4         X5   X6 X7
    1 TRUE N37.6 W089.0 201.1 1969-12-31 <NA>  1
    2 TRUE N37.6 W089.0 201.1 1969-12-31 <NA>  0

Unfortunately, it breaks if the `col_types` argument does not match the actual number of columns:

    read_fwf(text, col_pos, col_types = "c_c_c", skip = 1)
    Error in names(spec$cols) <- col_names : 
      'names' attribute [7] must be the same length as the vector [6]
    In addition: Warning message:
    Insufficient `col_types`. Guessing 1 columns.

**Comment by hadley** [comment] 2016-06-02 11:49
Duplicate of #322; possibly related to #371

**Closed by hadley** 2016-06-02 11:49 UTC
