### ISSUE TITLE
decimal separator and type detection

### ISSUE THREAD

**Issue by smbache** [hadley/readr#174] opened 2015-05-19 12:53 UTC
Here is an example where `col_euro_double()` fails, and where auto detection of column types fail when decimal separator is comma.

```R
library(readr)

# Fails to detect numeric type for the last two columns
read_delim(
"Date;Time;Volume;Price
01.03.2015;00:00 - 00:15;300,000;11,18
01.03.2015;00:15 - 00:30;-184,000;10,76
01.03.2015;00:30 - 00:45;-91,000;-1,51
01.03.2015;00:45 - 01:00;-290,000;12,42
", ";")

## Source: local data frame [4 x 4]
##
##         Date          Time   Volume Price
## 1 01.03.2015 00:00 - 00:15  300,000 11,18
## 2 01.03.2015 00:15 - 00:30 -184,000 10,76
## 3 01.03.2015 00:30 - 00:45  -91,000 -1,51
## 4 01.03.2015 00:45 - 01:00 -290,000 12,42

# Even specification of columns fails:
read_delim(
"Date;Time;Volume;Price
01.03.2015;00:00 - 00:15;300,000;11,18
01.03.2015;00:15 - 00:30;-184,000;10,76
01.03.2015;00:30 - 00:45;-91,000;-1,51
01.03.2015;00:45 - 01:00;-290,000;12,42
", ";", col_types = list(col_date("%d.%m.%Y"),
                         col_character(),
                         col_euro_double(),
                         col_euro_double()))

## Source: local data frame [4 x 4]
##
##         Date          Time Volume Price
## 1 2015-03-01 00:00 - 00:15    300 11.18
## 2 2015-03-01 00:15 - 00:30     NA 10.76
## 3 2015-03-01 00:30 - 00:45     NA    NA
## 4 2015-03-01 00:45 - 01:00     NA 12.42
## Warning message:
## 4 problems parsing literal data. See problems(...) for more details. 

```

**Comment by hadley** [comment] 2015-07-10 04:19
Duplicate of #213 and now fixed :)

**Closed by hadley** 2015-07-10 04:19 UTC
