### ISSUE TITLE
Looking for dates where there are none

### ISSUE THREAD

**Issue by briatte** [hadley/readr#235] opened 2015-08-21 09:51 UTC
I have been trying to integrate `readr` into several workflows where it would bring a real speed gain, but I am facing just one issue that makes it risky for me to do so.

It has to do with `readr` looking for dates where there are none. Here's an example:

```r
y = c("1989-90", "1990-91", "1991-92", "1992-93", "1993-94", "1994-95", 
      "1995-96", "1996-97", "1997-98", "1998-99", "1999-00", "2000-01", 
      "2001-02", "2002-03", "2003-04", "2004-05", "2005-06", "2006-07", 
      "2007-08", "2008-09", "2009-10", "2012-13", "2013-14", "2014-15", 
      "2015-16")
y = cbind(not_dates = y, x = 1)
write.csv(y, "test.csv", row.names = FALSE)
readr::read_csv("test.csv")
```

When faced with that example, `readr` 0.1.1 tries to interpret the first column as dates, fails to find a format, and thus returns `NA`.

The same problem arises if the data are of the form `"1989-1990", "1990-1991", ...`

Now, I know how to use `col_types`, but some of my workflows contain dozens of I/O calls from/to CSV files that have tons of columns, so using `readr` would require going through a lot of checks.

This is the only real trouble that I have faced with the package, so I thought I would ask: would you consider it reasonable – would it be possible – to have `readr` _not_ try to recognise strings of the form `\\d{4}-\\d{2}` or `\\d{4}-\\d{4}` as dates?

**Comment by hadley** [comment] 2015-08-21 11:54
Duplicate of #228

**Closed by hadley** 2015-08-21 11:54 UTC

**Comment by briatte** [comment] 2015-08-21 12:11
Oops, sorry!
