### ISSUE TITLE
Specifying `col_numeric` or `"n"` for `col_types` causes negative signs to be dropped

### ISSUE THREAD

**Issue by ateucher** [hadley/readr#350] opened 2016-01-08 18:19 UTC
Specifying `col_numeric` or `"n"` for `col_types` causes absolute values to be taken (negative signs are ignored).

```r
library(readr)

df <- data.frame(Col1 = c("a", "b", "c", "d", "e", "f"), 
                 Col2 = c(1.2, 2, -3.5, 0, -2.6, 5))

write_csv(df, "test.csv")

## Read with no specification of col_types (works as expected)
read_csv("test.csv")
```

```
##   Col1 Col2
## 1    a  1.2
## 2    b  2.0
## 3    c -3.5
## 4    d  0.0
## 5    e -2.6
## 6    f  5.0
```

```r
## Specifying double (works as expected)
read_csv("test.csv", col_types = "cd")
```

```
##   Col1 Col2
## 1    a  1.2
## 2    b  2.0
## 3    c -3.5
## 4    d  0.0
## 5    e -2.6
## 6    f  5.0
```

```r
## Specifying number (drops negatives)
read_csv("test.csv", col_types = "cn")
```

```
##   Col1 Col2
## 1    a  1.2
## 2    b  2.0
## 3    c  3.5
## 4    d  0.0
## 5    e  2.6
## 6    f  5.0
```

```r
## Specifying number with cols (drops negatives)
read_csv("test.csv", col_types = cols(Col1 = col_character(), Col2 = col_number()))
```

```
##   Col1 Col2
## 1    a  1.2
## 2    b  2.0
## 3    c  3.5
## 4    d  0.0
## 5    e  2.6
## 6    f  5.0
```

```r
sessionInfo()
```

```
## R version 3.2.3 (2015-12-10)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## Running under: Windows 7 x64 (build 7601) Service Pack 1
## 
## locale:
## [1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252   
## [3] LC_MONETARY=English_Canada.1252 LC_NUMERIC=C                   
## [5] LC_TIME=English_Canada.1252    
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
## [1] readr_0.2.2
## 
## loaded via a namespace (and not attached):
##  [1] magrittr_1.5    tools_3.2.3     htmltools_0.3   yaml_2.1.13    
##  [5] Rcpp_0.12.2     stringi_1.0-1   rmarkdown_0.9.2 knitr_1.12     
##  [9] stringr_1.0.0   digest_0.6.9    evaluate_0.8
```

**Comment by hadley** [comment] 2016-06-02 02:41
Duplicate of #308

**Closed by hadley** 2016-06-02 02:41 UTC
