### ISSUE TITLE
Option to load all columns as unprocessed characters with `col_character()`

### ISSUE THREAD

**Issue by jlegewie** [hadley/readr#204] opened 2015-06-24 14:06 UTC
It would be great to have an option that loads all columns as `col_character()`. Some csv are a mess and most columns don't work without some manual munging. If the number of columns is known, I can use `col_types = paste(rep("c", 10), collapse = "")`. But that is not always the case.

Here are two possibilities to implement this:
1) `col_types` accepts as "collector" function as an argument such as `col_types = col_character()` or `col_types = col_integer()`. All columns are processed in this way.
2) If a character of length 1 is passed to `col_types` (e.g. `col_types = "c"`), this type is used for all columns.

**Comment by hadley** [comment] 2015-09-03 21:15
Duplicate of #148

**Closed by hadley** 2015-09-03 21:15 UTC
