### ISSUE TITLE
Still having problem parsing time that is NA

### ISSUE THREAD

**Issue by johngoldin** [hadley/readr#344] opened 2016-01-05 03:26 UTC
Running 0.2.2.9000 but still unable to parse a date row that is NA.  Here is example:

> test_time = c("3:13 PM", NA)
> parse_time(test_time, format = "%H:%M %p")
Error: Invalid token
> parse_time(test_time[1], format = "%H:%M %p") # works OK without NA
[1] 15:13:00

> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.2 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] stringr_1.0.0    readr_0.2.2.9000 lubridate_1.5.0  dplyr_0.4.3     

loaded via a namespace (and not attached):
[1] magrittr_1.5   R6_2.1.1       assertthat_0.1 parallel_3.2.2 DBI_0.3.1      tools_3.2.2    Rcpp_0.12.2    stringi_1.0-1

**Comment by Ironholds** [comment] 2016-01-14 23:53
The preferable behaviour would be..a warning and an NA?

**Comment by hadley** [comment] 2016-06-02 02:41
Duplicate of #398, which is now fixed

**Closed by hadley** 2016-06-02 02:41 UTC
