### ISSUE TITLE
Need read_wsd() to more closely mimic read.table

### ISSUE THREAD

**Issue by dmenne** [hadley/readr#121] opened 2015-04-12 15:12 UTC
The file `nonmem.txt`   is output from a PK/PD program, truncated after a few lines. Original is 10000+
It reads Ok but slowly with `read.table`.

http://www.menne-biomed.de/uni/nonmem.txt

I don't want to report this as a bug, though, I might be missing something.

```
# Sample file can be downloaded from
# http://www.menne-biomed.de/uni/nonmem.txt
# This is output from NONMEM (PK/PD program)
# The full file is about 10000 lines and
# needs 60 seconds on my computer to load with read.table

str(read.table("nonmem.txt", header=TRUE)) # Fine, slow for large

library(readr)
str(read_table("nonmem.txt")) # Fast, but not correct
str(read_table("nonmem.txt", col_names=FALSE ,skip=1)) # Fast, no column names

library(data.table)
str(fread("nonmem.txt")) # error
str(fread("nonmem.txt"),skip=1, header=FALSE ) # error
sessionInfo()


R version 3.1.3 (2015-03-09)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
[3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.9.5    readr_0.1.0.9000    testthat_0.9.1.9001

loaded via a namespace (and not attached):
[1] chron_2.3-45   fortunes_1.5-2 Rcpp_0.11.5.1  tools_3.1.3   

```

**Comment by hadley** [comment] 2015-09-03 19:49
`read_table` has a slightly different interpretation of what a table is - `read_table()` looks for columns containing only whitespace; `read.table()` uses a delimited that's 1 or more whitespace.  I think `read_table()`'s behaviour is more useful in more places, but I do need an equivalent to `read.table()`.

**Comment by hadley** [comment] 2015-09-23 16:31
Now duplicate of #67

**Closed by hadley** 2015-09-23 16:31 UTC
