### ISSUE TITLE
a header-only CSV should probably not yield a one-row data frame

### ISSUE THREAD

**Issue by agoldst** [hadley/readr#260] opened 2015-09-15 13:12 UTC
`read_csv` behaves differently from `read.csv` in a degenerate case.

```r
read.csv(text="a,b\n", header=T, colClasses=c("character", "integer"))
```

```
## [1] a b
## <0 rows> (or 0-length row.names)
```

whereas

```r
read_csv("a,b\n", col_names=T, col_types="ci")
```

```
##      a  b
## 1 <NA> NA
```

with one row. I have actually encountered this, as outputs of an automatic process that generates many CSV's with identical headers, some of which contain no cases. It makes more sense, I think, to read such files as zero-row frames than as introducing a single row of `NA`s. Without `col_types` this gives an error.

And many thanks for yet another extraordinary package.

**Comment by hadley** [comment] 2015-09-15 23:56
Duplicate of #119

**Closed by hadley** 2015-09-15 23:56 UTC

**Comment by hadley** [comment] 2015-09-15 23:58
Thanks for the kind words :)

**Comment by agoldst** [comment] 2015-09-16 12:10
Oh rats, I'm sorry I missed this under #119 in my search of earlier issues. Apologies for the dupe! And thanks once again for all your work.
