### ISSUE TITLE
Connection broken after reading first chunk of rows

### ISSUE THREAD

**Issue by joehl** [hadley/readr#206] opened 2015-06-24 21:25 UTC
```R
# lets create data
write_csv(iris, "iris.csv")
con <- file("iris.csv", "rb")
# reading the first chunk from a connection works
read_csv(con, n_max=50)
# but autsch: can't continue reading from the connection
read_csv(con, n_max=50)
close(con)
```

Reading chunks from a connection (#16) is important (and read.csv can do it).
I know that there is a performance trade-off:
reading line-by-line with readLines() is slower than reading bigger chunks of bytes
but reading bigger chunks will usually read beyond the desired line break
and putting back to connections is costly and doesn't work everywhere (see #19).
A solution is adding a parameter for specifying *approx* chunk size

```R
read_csv(con, read_approx_bytes=5000)
```

So you can read a binary chunk of that size and then continue reading single bytes until the row is exhausted. For compatibility with read.csv you could actually allow both parameters, read_approx_bytes= and nrows= or n_max=. If someone asks for a precise number of lines, the slower readLines() (or a similar functionin C++) could be used.

**Comment by hadley** [comment] 2015-07-09 18:55
Duplicate of #76

**Closed by hadley** 2015-07-09 18:55 UTC
