### ISSUE TITLE
Readr loses negative values when reading

### ISSUE THREAD

**Issue by vzemlys** [hadley/readr#383] opened 2016-03-25 09:51 UTC
Compare the following:

```
library(readr)
library(dplyr)
read_csv("data.csv") %>% filter(Geographies == "Lithuania") %>% .[["Q1 2009"]]
read.csv("data.csv") %>% filter(Geographies == "Lithuania") %>% .[["Q1.2009"]]
```
The ```read_csv``` drops the negative sign. 

[data.csv.zip](https://github.com/hadley/readr/files/189318/data.csv.zip)

```
R version 3.2.3 (2015-12-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.3 (El Capitan)

locale:
[1] fr_FR.UTF-8/fr_FR.UTF-8/fr_FR.UTF-8/C/fr_FR.UTF-8/fr_FR.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.4.3 readr_0.2.2

loaded via a namespace (and not attached):
[1] lazyeval_0.1.10 magrittr_1.5    R6_2.1.2        assertthat_0.1 
[5] parallel_3.2.3  tools_3.2.3     DBI_0.3.1       Rcpp_0.12.3

```

**Comment by jennybc** [comment] 2016-03-25 15:37
Duplicate of #358. Related to #350 and #308.

**Closed** 2016-06-01 21:29 UTC
