### ISSUE TITLE
different decimal marks at once.

### ISSUE THREAD

**Issue by skanskan** [hadley/readr#376] opened 2016-03-03 15:40 UTC
It would be great to be able to define several decimal separators simultaneously.

For example I want to import a column with numbers no matter whether they use "." or ","  without the need of checking it.
read_table("name", decimal_mark = c(",","."))

**Comment by hadley** [comment] 2016-06-01 20:58
Duplicate of #308

**Closed by hadley** 2016-06-01 20:58 UTC
